# Generated by Django 5.1.1 on 2024-10-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deliveryFee',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount',
            field=models.IntegerField(default=0),
        ),
    ]
